### PR TITLE
set logger on the connection wrapper only

### PR DESCRIPTION
**Pull request by xabbuh**
The `Predis\Connection\Factory` class does not have a `setLogger()` method.

### CODE REVIEW

**Comment by B-Galati** [comment]
@xabbuh Thx! Could you target branch 2.1 as it's a bugfix please?

**Comment by xabbuh** [comment]
@B-Galati sure, rebase done

**Comment by micayael** [comment]
Hi. Is there any update on this?

**Comment by B-Galati** [comment]
@micayael Please try the fix and let us know if it works for you

**Comment by micayael** [comment]
> @micayael Please try the fix and let us know if it works for you

Yes. It works

**Comment by B-Galati** [comment]
I am not a fan of this solution as it would mean that logging could be activated but not working without knowing it. I would prefer something that throw a LogicException. What do you think all?

**Comment by xabbuh** [comment]
I am unfortunately not able to reproduce the initial bug report. I also think that such a solution could be a bit harder if the logging config and the connection class to be used cannot be evaluated at the same time.

I personally would merge this PR first to mitigate the reported issue and then think about how the issue you raised could be handled in a way that provides better feedback.

**Comment by B-Galati** [comment]
@xabbuh Could you rebase your work please? CI should be fixed after that.

**Comment by xabbuh** [comment]
Hm, one of the jobs is still failing. I am going to check what's causing this.

**Comment by B-Galati** [comment]
@xabbuh Looks weird, let me know if you need some help

**Comment by B-Galati** [comment]
The test is skipped on `master` branch as it is by nature unreliable so I guess we could do the same here.
Could you do so? I'll merge it then.

**Comment by xabbuh** [comment]
@B-Galati done

**Pull request merged**
