### PR TITLE
Revert "Enable Lazy service for phpredis (#440)"

### LINKED ISSUE #460: 2.1.5 is broken
`
Symfony\Component\Debug\Exception\ContextErrorException:
Warning: Redis::set() expects at least 2 parameters, 0 given

  at vendor\snc\redis-bundle\Client\Phpredis\Client.php:63
  at Snc\RedisBundle\Client\Phpredis\Client->call('set', array())
     (vendor\snc\redis-bundle\Client\Phpredis\Client.php:133)
  at Snc\RedisBundle\Client\Phpredis\Client->set()
     (var\cache\dev\ContainerBtpadub\Client_541ffe9.php:50)
  at Client_541ffe9->set('session5t3slmlkpj9as4nt72bsgetroq623lja.lock', '5b9e2dd7eee0f', array('NX', 'PX' => 180001))
     (vendor\snc\redis-bundle\Session\Storage\Handler\RedisSessionHandler.php:130)
  at Snc\RedisBundle\Session\Storage\Handler\RedisSessionHandler->Snc\RedisBundle\Session\Storage\Handler\{closure}(object(Client_541ffe9), 'session5t3slmlkpj9as4nt72bsgetroq623lja.lock', '5b9e2dd7eee0f', 180001)
     (vendor\snc\redis-bundle\Session\Storage\Handler\RedisSessionHandler.php:146)
  at Snc\RedisBundle\Session\Storage\Handler\RedisSessionHandler->lockSession('5t3slmlkpj9as4nt72bsgetroq623lja')
     (vendor\snc\redis-bundle\Session\Storage\Handler\RedisSessionHandler.php:205)
  at Snc\RedisBundle\Session\Storage\Handler\RedisSessionHandler->read('5t3slmlkpj9as4nt72bsgetroq623lja')
     (vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy.php:59)
  at Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy->read('5t3slmlkpj9as4nt72bsgetroq623lja')
  at session_start()
     (vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php:145)
  at Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start()
     (vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php:302)
  at Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->getBag('attributes')
     (vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Session.php:254)
  at Symfony\Component\HttpFoundation\Session\Session->getBag('attributes')
     (vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Session.php:276)
  at Symfony\Component\HttpFoundation\Session\Session->getAttributeBag()
     (vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Session.php:73)
  at Symfony\Component\HttpFoundation\Session\Session->get('_security_main')
     (vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ContextListener.php:89)ytghbtvktvj
`

i've got this after update.
I know about #449 and it is all gone #440 
It passed more then a month after u recognized that #440 is full of bugs
This is totally unacceptable !!!
U have to revert it

### PR DESCRIPTION
**Pull request by rvanlaak**
This reverts commit 2afed1dd

Fixes #460

### CODE REVIEW

**Comment by dkarlovi** [comment]
This breaks #434, a better solution is needed for #460.

**Comment by rvanlaak** [comment]
Can you elaborate and come up with a proposed direction for a solution? This way we still don't know how to help fix the BC break.

**Comment by dkarlovi** [comment]
@rvanlaak you've [quoted](https://github.com/snc/SncRedisBundle/issues/460#issuecomment-446117382) the desired solution?

> removing the lazy flag from a compiler pass if phpredis used and < 4.1.1.

About the BC break POV, I agree with @curry684 as stated [here](https://github.com/snc/SncRedisBundle/issues/460#issuecomment-427737788).

**Comment by dkarlovi** [comment]
So, this https://github.com/snc/SncRedisBundle/blob/b8f537b69a5709a64fac56431d262993f1265837/DependencyInjection/SncRedisExtension.php#L279

could be something like

```php
$phpredisDef->setLazy(version_compare(phpversion('redis'), '4.1.1', '>=')); 
```

Untested, should work. @B-Galati?

**Comment by rvanlaak** [comment]
@dkarlovi thanks, tested and confirmed as a working fix. See #481

**Comment by B-Galati** [comment]
@dkarlovi Looks great :+1: 
@rvanlaak Thx!

**Pull request closed without merging**
