### PR TITLE
#425 Use RedisDsn to build connection options for env based config 

### LINKED ISSUE #425: [v2.1.3] Unable to connect to Redis Resource in Azure
Hello, 

Yesterday I updated the Bundle in my Azure webapp and it seems there is a problem with the last version  changes. It's unable to connect to the Redis Resource in Azure showing this message:

`predis SELECT failed: NOAUTH Authentication required.`

The `REDIS_URL` is well defined and installing the version `2.1.2` it works properly.

Kind regards.

### PR DESCRIPTION
**Pull request by B-Galati**
fix #425

- Always use PredisParametersFactory to build connection options so that it creates consistency between env/non-env based config
- Use RedisDsn to parse redis DSN instead of \Predis\Connection\Parameters::parse(). It creates consistence between phpredis and predis behavior.

### CODE REVIEW

**Comment by B-Galati** [comment]
This pr depends on #432

**Comment by curry684** [comment]
Holding off on merge until Symfony 4.1.1 is out and therefore #432 can go in.

**Comment by B-Galati** [comment]
@curry684 You did well. It was the right order. I'll fix the conflicts tomorrow ;-)

**Comment by B-Galati** [comment]
@curry684 Done, it looks like it was a false positive conflict. Probably because I changed the commit sha1 of the based branch.

**Comment by curry684** [comment]
Thanks!

**Pull request merged**
