### PR TITLE
Improve testing & add Symfony 3 support

### PR DESCRIPTION
**Pull request by WouterJ**
Todo
---

 * [x] Fix DataCollector templates for the new 2.8/3.0 toolbar/profiler.

### CODE REVIEW

**Comment by snc** [comment]
This is awesome! Great work so far :+1:

**Comment by WouterJ** [comment]
Updated the PR to add tests for the RedisLogger and to enable the redis server on travis, so Travis will no longer skip 50% of the tests. This also revealed a bug in RedisCache.

**Comment by WouterJ** [comment]
Added the updated templates/icons for the new toolbar/profiler. Screenshots (generated with dummy data):

Toolbar
---

#### No commands executed

Icon is hidden, which is the convention in 2.8+.

#### Commands executed

sf-redis-toolbar-commands

#### Failed commands

sf-redis-toolbar-commands-error

Profiler
---

#### No commands executed

sf-redis-no-commands

#### Commands executed

sf-redis-commands

#### Failed commands

sf-redis-commands-error

I haven't tested the templates with the older toolbar, but it should be correct (will test this week).

**Comment by MaximeThoonsen** [comment]
Nice =). Thanks @WouterJ ! I hope you can finish that soon !

**Comment by MaximeThoonsen** [comment]
I added one PR to this PR: https://github.com/WouterJ/SncRedisBundle/pull/1

**Comment by WouterJ** [comment]
Just tested it in a 2.7 app and everything looked correct. When Travis is green, this PR is ready to merge. (maybe there still are some deprecated usages in the code because tests do not cover anything, but users of this bundle will report them)

**Comment by snc** [comment]
Thanks for the great work!

**Comment by WouterJ** [comment]
No problem :)

**Comment by stof** [comment]
@snc do you have an ETA for a stable release including this work ? The stable versions of the bundle are currently incompatible with Symfony 3 (and throw deprecations in 2.8)

**Comment by snc** [comment]
I really would like to solve #184 before releasing a 2.0 version because this might break BC for some specific use cases.

**Pull request merged**
