### PR TITLE
Fixed adding service locator into container & commands

### LINKED ISSUE #520: ClientLocatorPass::createClientLocatorDefinition : add definition without id.
Symfony version: 4.3.1
SncRedisBundle: master

https://github.com/snc/SncRedisBundle/blob/master/DependencyInjection/Compiler/ClientLocatorPass.php#L99

`$container->addDefinitions([$clientLocatorDefinition]);` of 
`\Snc\RedisBundle\DependencyInjection\Compiler\ClientLocatorPass::createClientLocatorDefinition` is set service definition of `int(0)` id.

Please set string id.
Other bundles are based on the assumption that id is string type.

### PR DESCRIPTION
**Pull request by stloyd**
This follows the Symfony documention for creating & managing service locators:
https://symfony.com/doc/3.4/service_container/service_subscribers_locators.html#defining-a-service-locator

Fixes #520

### CODE REVIEW

**Comment by stloyd** [comment]
Ping @ochi51 @B-Galati

**Comment by stloyd** [comment]
Anything missing @B-Galati ? I would say that without this change everyone using `3.1.0` version needs to downgrade it, cause it's not usable at all due too the bug fixed here.

**Comment by B-Galati** [comment]
@stloyd Thank you! I'll catch up ASAP.

**Comment by stloyd** [comment]
@B-Galati Friendly ping :) Mostly cause this blocked our update of library :(

**Comment by B-Galati** [comment]
@stloyd many changes that are not easy to review, so it will take some time. I don't have a lot of time for the bundle these days.

**Comment by rpkamp** [comment]
> This follows the Symfony documention for creating & managing service locators:

I don't see that this PR does that. It looks like it's just injecting the entire service container into the BaseRedisCommand. Which works, but gives the command quite a lot of access.

The solution outlined in the documentation you linked to, actually creating a `ServiceLocator` instance, looks a lot nicer than what this PR proposes.

**Comment by rpkamp** [comment]
See https://github.com/snc/SncRedisBundle/pull/535

**Comment by B-Galati** [comment]
@stloyd Closing that PR as per @rpkamp comments

I tried to integrate some of your changes but some are unrelated. Please try to keep your PR as focus as possible in the future.

You can open another one if you want to integrate some of your refactoring.

Thank you for your work!

**Pull request closed without merging**
