### PR TITLE
Updated Predis to work with 1.*, not 0.8

### PR DESCRIPTION
**Pull request by mattmontgomery**
I'm not sure if you'll have any use for this or be interested in any of the changes, but these are changes I made to get SncRedisBundle working with Predis 1.0 -- take them or leave them. Tests look to be passing (with two failures that were present before the changes I've made.)

### CODE REVIEW

**Comment by ooflorent** [comment]
Any news here?

**Comment by garak** [comment]
:+1:

**Comment by Divi** [comment]
:+1:

**Comment by penfold45** [comment]
Hi is there a reason this has not been merged in yet?

I just tried to update to predis 1.0.8 and got

    PHP Fatal error:  Class 'Predis\Profile\ServerProfile' not found in vendor/snc/redis-bundle/Snc/RedisBundle/DependencyInjection/SncRedisExtension.php on line 158

Which this pull request appear to fix

**Comment by theUniC** [comment]
There is a second PR, https://github.com/snc/SncRedisBundle/pull/172, to continue with the work from @mattmontgomery.

Unfortunately, this project appears to be discontinued since the owner has not say anything and there is no commits / merges since September from last year :(

**Comment by penfold45** [comment]
Oh I hadn't noticed that. That's a great shame if this is dead :(

**Comment by snc** [comment]
I haven't noticed this, too, sorry, #172 got merged.

**Pull request closed without merging**
