### PR TITLE
Change configuration to allow config values required for redis sentinel

### PR DESCRIPTION
**Pull request by pascal-hofmann**
This allows for supplying the required values for redis sentinel (supported by Predis 1.1.x, out soon). See https://github.com/nrk/predis/issues/131#issuecomment-219053799 . Unfortunately the password is somehow not used when connecting to the redis master. After hours of debugging I worked around this by creating a **very** hacky custom connection factory (at the moment I simply have no time for a proper solution. Maybe someone else has...):

```
class ConnectionFactory extends \Snc\RedisBundle\Client\Predis\Connection\ConnectionFactory
{
    private $masterPassword = null;

    public function create($parameters)
    {
        if (isset($parameters['parameters']['password'])) {
            $this->masterPassword = $parameters['parameters']['password'];
        }
        if ((int) $parameters['port'] === 6379) {
            $parameters['password'] = $this->masterPassword;
        }

        return parent::create($parameters);
    }

}
```

### CODE REVIEW

**Comment by AlexC** [comment]
@phofmann-trust  What was your snc_redis config to allow support for Sentinels? From what I can see, whilst Predis now supports Sentinel, SncRedisBundle does not

**Comment by phofmann-trust** [comment]
Did this for my old job. Don't have access to working configuration/source code anymore. Sorry :(

I remember that I had to do some other magic to get fully working Sentinel support with SncRedisBundle (some kind of config provider hack? Hm...)

thumbtyped, please excuse brevity and typos

**Comment by ivoba** [comment]
+1 for sentinel support

i worked around this with overriding the predis client service definitions in production since the main benefit of this bundle for me is logging & webprofiler, thus dev things which can be omitted in production.

```
snc_redis.default:
        class: Predis\Client
        arguments: ['%live.redis.sentinels%', '%live.default.redis.options%']
```

**Comment by asev** [comment]
+1 for redis sentinel support

**Comment by pascal-hofmann** [comment]
Closing this because it is now supported with version 2.

**Pull request closed without merging**
