### PR TITLE
Increase the cut-limit for a command

### PR DESCRIPTION
**Pull request by goetas**
This will make logs more readable

### CODE REVIEW

**Comment by snc** [comment]
Thanks, merged.

**Comment by Seldaek** [comment]
Why not remove this substr()/toStringArgumentReducer entirely? It's the job of the profiler UI to restrict the data shown if needed IMO, but the logs shouldn't be truncated :/ I didn't find any reason why this was added in https://github.com/snc/SncRedisBundle/pull/172 (cc @theUniC).

**Comment by theUniC** [comment]
In #172 I only continued with a previous work to make this bundle work with PRedis 1.0 in #150.

**Comment by Seldaek** [comment]
OK so it was @mattmontgomery who did it, I missed that. Any clue about the issue here @mattmontgomery? :)

**Pull request merged**
