### PR TITLE
 #182 token serialization while lock remove

### PR DESCRIPTION
**Pull request by piotrkochan**
This change just applies serialization on the token lock value

### CODE REVIEW

**Comment by piotrkochan** [comment]
anyone?

**Comment by curry684** [comment]
Thanks @piotrkochan !

**Comment by piotrkochan** [comment]
Yes, it does

**Comment by curry684** [comment]
Not sure what's holding Symfony 4.1.1 this long, there's other changes pending which require a bugfix in there.

**Comment by piotrkochan** [comment]
I hope this be released 2.1.4 soon

**Comment by curry684** [comment]
https://github.com/snc/SncRedisBundle/releases/tag/2.1.4   👍

**Comment by max4ever** [comment]
I think this MR actually introduced this https://github.com/snc/SncRedisBundle/issues/676 😅

**Pull request merged**
