### PR TITLE
make phpredis work with lazy doctrine caches

### LINKED ISSUE #578: Lazy config is not working with phpredis.
I've noticed that a lazy config with phpredis and doctrine still requires a connection to the server, otherwise it fails:

I ran a `bin/console cache:clear` in my Dockerfile and noticed this bug.

The `snc_redis.<name>` services are lazy, but the `\Snc\RedisBundle\DependencyInjection\SncRedisExtension::loadDoctrine` provides this `$definitionFunction`:

```php
case 'phpredis':
    $definitionFunction = function ($client, $cache) use ($container) {
    $def = new Definition($container->getParameter('snc_redis.doctrine_cache_phpredis.class'));
    $def->addMethodCall('setRedis', array($client));
    if ($cache['namespace']) {
      $def->addMethodCall('setNamespace', array($cache['namespace']));
    }
    return $def;
  };
  break;
```
Seems okay and somehow "lazy", but once the actual `\Doctrine\Common\Cache\RedisCache::setRedis` call is made (e.g. during container warmup) it calls `$redis->setOption(Redis::OPT_SERIALIZER, $this->getSerializerValue());` on the proxy which will be instantiated immediately, which calls `\Snc\RedisBundle\Factory\PhpredisClientFactory::createClient` which includes this:

```php
if (!empty($options['connection_persistent'])) {
 $client->pconnect(...$connectParameters);
} else {
 $client->connect(...$connectParameters);
}
```
...but there is no connection. :(

I'll provide a pull request with a solution in a few minutes.

Hotfix in my app: Manually tagging all `doctrine.orm.**_cache` definitions lazy in a CompilerPass.

### PR DESCRIPTION
**Pull request by Basster**
Hopefully fixes #578

### CODE REVIEW

**Comment by B-Galati** [comment]
Closing as per issue comment saying that it is fixed.

**Comment by progmancod** [comment]
Guys, this is a NO solution. The solution in the comment issue take doctrine system cache out from redis at all:

doctrine.system_cache_pool:
adapter: cache.system

We still need this pull request.

**Comment by B-Galati** [comment]
What's the issue with that?

**Comment by progmancod** [comment]
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Doctrine\Common\Cache\RedisCache::setRedis() must be an instance of Redis, instance of Container1WKlMkT\RedisCluster_8dcfeee given, called in /var/www/html/var/cache/prod/Container1WKlMkT/SuppCore_AdministrativoBackend_KernelProdDebugContainer.php on line 1568 and defined in /var/www/html/vendor/doctrine/cache/lib/Doctrine/Common/Cache/RedisCache.php:31

**Comment by B-Galati** [comment]
It looks like you're using RedisCluster while doctrine cache does not support it.

I don't get how it relates. Please open a detail issue if you think there is one.

**Pull request closed without merging**
