### PR TITLE
fix create doctrine cache difinition when predis is client

### PR DESCRIPTION
**Pull request by shustrik**
Fix doctrine cache definition when cache client is predis. Doctrine\Common\Cache\PredisCache has constructor with ClientInterface parameter, but now client is set from method injection setRedis.

### CODE REVIEW

**Comment by snc** [comment]
Symfony 2.7 has PHP `>=5.3.9` as requirement, could you please switch to the old `array()` syntax so that it runs with those old versions?

**Comment by shustrik** [comment]
fixed

**Comment by snc** [comment]
Would be nice if you could squash your commits into one.

**Comment by shustrik** [comment]
fixed

**Comment by snc** [comment]
Nice, thanks.

**Pull request merged**
