### PR TITLE
Support predis 2

### LINKED ISSUE #664: Support predis 2.0
Hi,

It seems that upgrading to predis 2.0 is causing trouble. 

I got this error when I tried :

!  Symfony\Component\ErrorHandler\Error\ClassNotFoundError {#72
!!    #message: """
!!      Attempted to load class "Factory" from namespace "Predis\Profile".\n
!!      Did you forget a "use" statement for e.g. "Predis\Command\Factory", "Predis\Connection\Factory", "JsonSchema\Constraints\Factory" or "Doctrine\DBAL\Driver\IBMDB2\Exception\Factory"?
!!      """
!!    #code: 0
!!    #file: "./vendor/snc/redis-bundle/src/DependencyInjection/SncRedisExtension.php"
!!    #line: 170
!!    trace: {
!!      ./vendor/snc/redis-bundle/src/DependencyInjection/SncRedisExtension.php:170 { …}
!!      ./vendor/snc/redis-bundle/src/DependencyInjection/SncRedisExtension.php:117 { …}
!!      ./vendor/snc/redis-bundle/src/DependencyInjection/SncRedisExtension.php:68 { …}
!!      ./vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:76 { …}
!!      ./vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:42 { …}
!!      ./vendor/symfony/dependency-injection/Compiler/Compiler.php:82 { …}
!!      ./vendor/symfony/dependency-injection/ContainerBuilder.php:757 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:546 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:787 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:128 { …}
!!      ./vendor/bref/symfony-bridge/src/BrefKernel.php:62 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:168 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:74 { …}
!!      ./vendor/symfony/console/Application.php:171 { …}
!!      ./vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:54 { …}
!!      ./vendor/autoload_runtime.php:35 { …}
!!      ./bin/console:12 {
!!        ›
!!        › require_once dirname(__DIR__).'/vendor/autoload_runtime.php';
!!        ›
!!        arguments: {
!!          "/var/www/html/vendor/autoload_runtime.php"
!!        }
!!      }
!!    }
!!  }
!!  2022-06-08T18:33:11+00:00 [critical] Uncaught Error: Class "Predis\Profile\Factory" not found
!!

Best,
Julien

### PR DESCRIPTION
**Pull request by franmomu**
Closes #664

This PR is an attempt to support predis 2, it breaks BC since it's removing the `profile` configuration option (removed in predis 2).

It's in draft since I haven't tried it yet in a real project and if this is fine, an upgrade note should be written.

### CODE REVIEW

**Comment by ostrolucky** [comment]
These changes are quite small and people relying on `profile` won't be able to update anyways, because they have to be pinned to predis 1.x. So I would go with changing this in minor release already.

**Comment by franmomu** [comment]
ok so shall I deprecated the `profile` option (removing all the service definitions)? or just remove it

**Comment by ostrolucky** [comment]
Just removing it is fine. Is there anything left to do in this PR?

**Comment by franmomu** [comment]
in my project works fine (I use a very simple configuration), more testing in real projects would be nice.

**Pull request merged**
