### PR TITLE
adding autodiscover

### PR DESCRIPTION
**Pull request by oleg-andreyev**
Adding autodiscover option

### CODE REVIEW

**Comment by curry684** [comment]
Is this compatible with PhpRedis?

**Comment by oleg-andreyev** [comment]
It was long time ago, I'll have to recheck

**Comment by oleg-andreyev** [comment]
Seems that PhpRedis does not have native support of autodiscovery not replication (https://github.com/phpredis/phpredis/issues/663) and should be done on application level

**Comment by curry684** [comment]
Expected as much, but I'm afraid that means this PR would or could break things when used with PhpRedis? At the very least we'd have to issue some sort of warning that this feature is not available, or throw an explicit error perhaps.

**Comment by curry684** [comment]
I'm still open to merging this feature, but it would have to do proper checking that it is only applied to Predis connections.

**Comment by oleg-andreyev** [comment]
@curry684 sorry, I didn't had time to review PhpRedis, I'll try to make it be the end of the week.

**Comment by curry684** [comment]
Last call for changes or additions, closing next time.

**Comment by oleg-andreyev** [comment]
Sorry. I haven't worked with redis for a long time.

**Pull request closed without merging**
