### PR TITLE
serializer option for redis client

### PR DESCRIPTION
**Pull request by edast**
based on #130 
removed all changes not related to serialization option

### CODE REVIEW

**Comment by yellow1912** [comment]
So this PR did not passed the test etc, but I think we are in serious need to control the way serializer is used in redis. In my use case I would like to store simple strings in redis that will be read by non php script so I would like to have the option to set serializer to none.

**Comment by Webonaute** [comment]
can we have some fix for this ?

**Comment by piotrkochan** [comment]
There is 4 PR's for Serializer configuration, I can't believe nobody cares about them.

**Comment by curry684** [comment]
@edast we're picking up some overdue late maintenance work, any chance you can rebase?

**Comment by curry684** [comment]
Closed in favor of #411

**Pull request closed without merging**
