### PR TITLE
Autoconfigure RedisBaseCommand to add snc_redis.command tag

### PR DESCRIPTION
**Pull request by maxhelias**
Autoconfigure instances of `Snc\RedisBundle\Command\RedisBaseCommand` to add `snc_redis.command` tag

### CODE REVIEW

**Comment by B-Galati** [comment]
Should we remove the tag `snc_redis.command` from `redis.xml` too?

**Comment by maxhelias** [comment]
I really do not know why the configuration that is retrieved from the redis.xml file is not update. But when I test my custom redis commands of my project it works well.

There would not be a particularity on the conf files ? I see on the Symfony project, the command tag is redefined.

**Comment by rpkamp** [comment]
FYI the entire tag will be obsolete if https://github.com/snc/SncRedisBundle/pull/533 is merged.

**Comment by B-Galati** [comment]
Thanks @maxhelias

**Comment by B-Galati** [comment]
I don't get why you're saying that command tag would be obsolete?

It's still needed to inject the service locator no?

**Comment by B-Galati** [comment]
> I really do not know why the configuration that is retrieved from the redis.xml file is not update. But when I test my custom redis commands of my project it works well i see the tag and i don't see the tag on `flushhdb` command if i remove it on the config file.
> 
> There would not be a particularity on the conf files ? I see on the Symfony project, the command tag is redefined.

@maxhelias I tried and don't get that behavior either so :+1:

**Comment by B-Galati** [comment]
Any hint @nicolas-grekas ?

**Comment by rpkamp** [comment]
If we'd merged #533 it would be obsolete. But we didn't, because #533 was a bad idea.

So, it's not obsolete, this PR is a good idea, and it should be merged :slightly_smiling_face:

**Comment by B-Galati** [comment]
All clear now thanks!

**Pull request merged**
