### PR TITLE
Support encrypted connection via phpredis

### PR DESCRIPTION
**Pull request by benburleson**
Fixes https://github.com/snc/SncRedisBundle/issues/562

### CODE REVIEW

**Comment by B-Galati** [comment]
Can you rebase your branch? I fixed the CI.

**Comment by B-Galati** [comment]
Could you also add some tests too please?

**Comment by benburleson** [comment]
I has originally added a test, but then realized Travis only spins up a
basic Redis service, so I'm not sure how I'm able to test the tls
connection. Open to ideas..

I'll rebase when I'm back in the office later this morning.

Thank you!

**Comment by B-Galati** [comment]
> I has originally added a test, but then realized Travis only spins up a basic Redis service, so I'm not sure how I'm able to test the tls connection. Open to ideas..

Yea you're right. I have no idea as I am not using this feature myself.

**Comment by benburleson** [comment]
> Yea you're right. I have no idea as I am not using this feature myself.

Yeah, with the ease of services like Elasticache (and enabling encryption with a simple option), it's now a hassle to stand up your own Redis instance with custom configs.

Hoping we can just merge this with the caveat that tls via phpredis is not fully tested.

Thanks for your help and maintenance of this very useful package!

**Comment by B-Galati** [comment]
Thanks @benburleson

**Pull request merged**
