### PR TITLE
Deprecate session integration

### PR DESCRIPTION
**Pull request by ostrolucky**

### CODE REVIEW

**Comment by B-Galati** [comment]
Not sure @Seldaek is going to like this or not ^^

Perhaps there are still some good reasons to use this one VS symfony one?

**Comment by Seldaek** [comment]
I definitely will have to investigate further. I know I am using this bundle's handler on a few high traffic applications..

**Comment by ostrolucky** [comment]
Well please let me know as soon as possible, I plan to release 4.0 pretty soon. But if there are whatever improvements that are missing from Symfony session handler, they should be added to symfony one IMHO.

**Comment by frankverhoeven** [comment]
Hi there! To add my two cents, we use this session handler because it provides locking, while the Syfmony one does not (it's described in [their docs](https://symfony.com/doc/current/session/database.html#store-sessions-in-a-key-value-database-redis) as caveat)

**Comment by Seldaek** [comment]
Right, I am not actually relying on locking so for me no worries. I can definitely use the native Symfony handler. 

@frankverhoeven If you do require locking (I find it is usually causing more problems than anything) perhaps it's best to send a PR to symfony to add optional locking there? It's not that much code to port over.

**Comment by adrienfr** [comment]
Hi, actual [SF documentation](https://symfony.com/doc/current/session/database.html#store-sessions-in-a-key-value-database-redis) regarding Redis for sessions management is to :

1. Define a Redis connection
```yml
# config/services.yaml
services:
    Redis:
        # you can also use \RedisArray, \RedisCluster or \Predis\Client classes
        class: Redis
        calls:
            - connect:
                - '%env(REDIS_HOST)%'
                - '%env(int:REDIS_PORT)%'
```
2. Then send this `Redis` to `RedisSessionHandler`:
```yml
# config/services.yaml
services:
    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@Redis'
            # - { 'prefix': 'my_prefix', 'ttl': 600 }
```
3. And finally use this `handler_id` to manage sessions through Redis:
```yml
# config/packages/framework.yaml
framework:
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
```

Is there any way to use a client already defined in `snc_redis` in step 1. or/and 2. instead of duplicating redis server information :
```yml
# config/packages/snc_redis.yaml
snc_redis:
    clients:
        sessions:
            type: predis
            alias: sessions
            dsn: "redis://%redis.session.host%"
```

**Comment by adrienfr** [comment]
Seems to be working : forget about step 1. and replace with this in step 2.
```yaml
Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@snc_redis.sessions'
            # - { 'prefix': 'my_prefix', 'ttl': 600 }

**Comment by ostrolucky** [comment]
Yes, this has been documented at https://github.com/snc/SncRedisBundle/blob/4.x/Resources/doc/index.md#sessions

**Pull request merged**
